"""
Generate RAVIN backend source documentation.

The generated documents record only implemented and verified backend work.
They are source material for later project-wide guides.

Generated Markdown files should not be edited directly. Update this
generator and rerun it so documentation changes remain reproducible.
"""

from __future__ import annotations
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIRECTORY = REPOSITORY_ROOT / "docs"

DOCUMENTS = {'backend-architecture.md': '> **Implementation scope:** RAVIN backend workstream\n'
                            '>\n'
                            '> **Backend checkpoint:** `5c8e2ce`\n'
                            '>\n'
                            '> **Verification baseline:** 725 passing tests\n'
                            '>\n'
                            '> **Purpose:** Source material for later project-wide documentation\n'
                            '\n'
                            '# RAVIN Backend Architecture\n'
                            '\n'
                            '## 1. Purpose\n'
                            '\n'
                            'This document describes the backend architecture implemented for '
                            'RAVIN.\n'
                            '\n'
                            'It deliberately excludes unimplemented or separately owned '
                            'application components. In particular, the final FastAPI application '
                            'layer and user interface are integration consumers of this backend '
                            'rather than backend components documented here as completed work.\n'
                            '\n'
                            '## 2. Backend Objective\n'
                            '\n'
                            'RAVIN is designed as an evidence-first policy question-answering '
                            'backend.\n'
                            '\n'
                            'The implemented backend separates evidence discovery, evidence '
                            'sufficiency, answer routing, language generation, and answer '
                            'release.\n'
                            '\n'
                            'The principal flow is:\n'
                            '\n'
                            '```text\n'
                            'Current policy sources\n'
                            '-> acquisition\n'
                            '-> normalization and chunking\n'
                            '-> semantic index\n'
                            '-> hybrid retrieval\n'
                            '-> reranking\n'
                            '-> structural context assembly\n'
                            '-> question intent assessment\n'
                            '-> material proposition extraction\n'
                            '-> evidence coverage assessment\n'
                            '-> deterministic answer routing\n'
                            '-> grounded answer generation\n'
                            '-> citation validation\n'
                            '-> generated-claim grounding validation\n'
                            '-> application-facing answer result\n'
                            '```\n'
                            '\n'
                            'The important architectural rule is that a generative language model '
                            'does not decide question intent, evidence sufficiency, or answer '
                            'behavior.\n'
                            '\n'
                            '## 3. Main Backend Areas\n'
                            '\n'
                            '### `backend/ingestion`\n'
                            '\n'
                            'Responsible for acquiring policy content, validating that policy '
                            'material is current, normalizing text, preserving heading structure, '
                            'and producing traceable `PolicyChunk` objects.\n'
                            '\n'
                            'Each chunk retains:\n'
                            '\n'
                            '- policy identifier\n'
                            '- policy title\n'
                            '- source URL\n'
                            '- status\n'
                            '- effective and review dates\n'
                            '- chunk index\n'
                            '- text\n'
                            '- heading path\n'
                            '\n'
                            'This provenance is preserved so retrieved evidence can later be '
                            'traced back to the originating policy.\n'
                            '\n'
                            '### `backend/retrieval`\n'
                            '\n'
                            'Responsible for finding and organising candidate policy evidence.\n'
                            '\n'
                            'Production retrieval performs:\n'
                            '\n'
                            '```text\n'
                            'query\n'
                            '-> query embedding\n'
                            '-> semantic + lexical hybrid scoring\n'
                            '-> candidate selection\n'
                            '-> cross-encoder reranking\n'
                            '-> final Top-K evidence\n'
                            '-> bounded structural neighbour expansion\n'
                            '-> grounded evidence blocks\n'
                            '```\n'
                            '\n'
                            'Production embeddings use policy body text.\n'
                            '\n'
                            'The index also retains richer retrieval text containing policy title, '
                            'heading path, and body text for lexical scoring and reranking.\n'
                            '\n'
                            'Retrieval scores are ranking signals. They do not independently '
                            'determine whether the evidence is sufficient to answer the question.\n'
                            '\n'
                            '### `backend/routing`\n'
                            '\n'
                            'Responsible for deterministic question interpretation, evidence '
                            'sufficiency, and answer behavior.\n'
                            '\n'
                            'Implemented answer behaviors are:\n'
                            '\n'
                            '- `DIRECT_ANSWER`\n'
                            '- `GROUNDED_OVERVIEW`\n'
                            '- `CLARIFY`\n'
                            '- `NO_GROUNDED_ANSWER`\n'
                            '\n'
                            'The routing rules are:\n'
                            '\n'
                            '```text\n'
                            'ambiguous question\n'
                            '-> CLARIFY\n'
                            '\n'
                            'clear question + insufficient/uncertain evidence\n'
                            '-> NO_GROUNDED_ANSWER\n'
                            '\n'
                            'focused question + sufficient evidence\n'
                            '-> DIRECT_ANSWER\n'
                            '\n'
                            'broad question + sufficient evidence\n'
                            '-> GROUNDED_OVERVIEW\n'
                            '```\n'
                            '\n'
                            'Ambiguous questions do not proceed through evidence sufficiency '
                            'assessment because the question must first be clarified.\n'
                            '\n'
                            '### `backend/generation`\n'
                            '\n'
                            'Responsible for grounded answer wording and post-generation '
                            'validation.\n'
                            '\n'
                            'Generation receives:\n'
                            '\n'
                            '- the user question\n'
                            '- an already selected answer behavior\n'
                            '- approved evidence text\n'
                            '\n'
                            'It does not select its own behavior.\n'
                            '\n'
                            'Generated answers must pass:\n'
                            '\n'
                            '```text\n'
                            'generation\n'
                            '-> evidence citation validation\n'
                            '-> claim-to-evidence grounding validation\n'
                            '-> release\n'
                            '```\n'
                            '\n'
                            'Unsupported generated output is rejected rather than returned as a '
                            'grounded answer.\n'
                            '\n'
                            '### `backend/llm`\n'
                            '\n'
                            'Provides the replaceable language-model provider boundary.\n'
                            '\n'
                            'The current local adapter communicates with Ollama, while the '
                            'remainder of the backend depends on the neutral '
                            '`LanguageModelProvider` contract.\n'
                            '\n'
                            '### `backend/evaluation`\n'
                            '\n'
                            'Provides retrieval and routing evaluation, experiment comparison, '
                            'quality gates, dataset loading, and reproducibility evidence.\n'
                            '\n'
                            'The evaluation code explicitly distinguishes preliminary development '
                            'datasets from human-validated datasets.\n'
                            '\n'
                            '### `backend/service`\n'
                            '\n'
                            'Provides the application-facing integration boundary.\n'
                            '\n'
                            '`RavinAnswerService` coordinates retrieval, routing, generation, '
                            'validation, and source mapping.\n'
                            '\n'
                            'Application adapters should call:\n'
                            '\n'
                            '```python\n'
                            'result = service.answer(question)\n'
                            '```\n'
                            '\n'
                            'rather than reimplementing individual backend stages.\n'
                            '\n'
                            '## 4. Shared Startup Architecture\n'
                            '\n'
                            'The shared bootstrap is:\n'
                            '\n'
                            '```text\n'
                            'backend/service/bootstrap.py\n'
                            '-> acquire current policies\n'
                            '-> process policy chunks\n'
                            '-> load runtime configuration\n'
                            '-> construct providers\n'
                            '-> build retrieval index\n'
                            '-> construct RavinAnswerService\n'
                            '```\n'
                            '\n'
                            'The resulting service is intended to be constructed once during '
                            'application startup and reused.\n'
                            '\n'
                            'This avoids repeatedly downloading policies, loading model weights, '
                            'rebuilding embeddings, rebuilding the retrieval index, and '
                            'reconstructing backend services for each user request.\n'
                            '\n'
                            '## 5. Replaceable Provider Architecture\n'
                            '\n'
                            'Concrete models and libraries are kept behind provider contracts.\n'
                            '\n'
                            'Implemented provider boundaries include:\n'
                            '\n'
                            '- embedding provider\n'
                            '- reranker provider\n'
                            '- question parser provider\n'
                            '- answerability provider\n'
                            '- entailment provider\n'
                            '- language-model provider\n'
                            '\n'
                            'Provider selection is resolved in the composition layer rather than '
                            'inside business logic.\n'
                            '\n'
                            'This allows model replacement without rewriting retrieval, routing, '
                            'or service orchestration.\n'
                            '\n'
                            '## 6. Parser Boundary\n'
                            '\n'
                            'spaCy currently supplies linguistic analysis through an adapter.\n'
                            '\n'
                            'spaCy concepts such as token part-of-speech and dependency labels are '
                            'converted into RAVIN-neutral parse structures.\n'
                            '\n'
                            'Higher-level concepts including material requirements, material '
                            'propositions, RELATION, CONDITION, CONCEPT, REQUESTED_ATTRIBUTE, and '
                            'RECOVERY are RAVIN concepts rather than spaCy concepts.\n'
                            '\n'
                            '## 7. Plain-English Retrieval Concepts\n'
                            '\n'
                            '### Embeddings\n'
                            '\n'
                            'An embedding converts text into a numerical vector that represents '
                            'aspects of its meaning.\n'
                            '\n'
                            'RAVIN uses embeddings so a policy passage can still be considered '
                            'relevant when it does not contain exactly the same words as the '
                            "user's question.\n"
                            '\n'
                            'For example, a question about a student "not progressing '
                            'satisfactorily" may still be semantically close to policy text '
                            'describing "unsatisfactory academic progress", even though the '
                            'wording is not identical.\n'
                            '\n'
                            'The production embedding vectors contain many dimensions. A '
                            'simplified two-dimensional example is useful for explaining the '
                            'comparison.\n'
                            '\n'
                            'Assume:\n'
                            '\n'
                            '```text\n'
                            'query vector   -> (1, 1)\n'
                            'policy chunk A -> (1, 1)\n'
                            'policy chunk B -> (1, 0)\n'
                            '```\n'
                            '\n'
                            '### Cosine Similarity\n'
                            '\n'
                            'Cosine similarity compares the direction of two vectors.\n'
                            '\n'
                            'For the query and policy chunk A, cosine similarity is `1.0` because '
                            'their directions are identical.\n'
                            '\n'
                            'For the query and policy chunk B:\n'
                            '\n'
                            '```text\n'
                            'cosine similarity\n'
                            '= (1 x 1 + 1 x 0)\n'
                            '  / (sqrt(2) x 1)\n'
                            '= approximately 0.707\n'
                            '```\n'
                            '\n'
                            'Chunk A is therefore more semantically similar to the query in this '
                            'simplified example.\n'
                            '\n'
                            'RAVIN does not use cosine similarity as a final evidence-sufficiency '
                            'decision. Production retrieval also applies lexical scoring and '
                            'cross-encoder reranking, and later routing separately assesses '
                            'whether the retrieved evidence is sufficient to answer the question.\n'
                            '\n'
                            '## 8. Application Boundary\n'
                            '\n'
                            'The backend currently exposes its completed behavior through '
                            '`RavinAnswerService`.\n'
                            '\n'
                            'The CLI is an implemented application adapter.\n'
                            '\n'
                            'A FastAPI adapter can use the same service boundary without '
                            'duplicating retrieval or RAG implementation. An example is provided '
                            'in `backend-handover.md`.\n'
                            '\n'
                            '## 9. Scope Boundary\n'
                            '\n'
                            'This document does not claim completion of:\n'
                            '\n'
                            '- the final FastAPI application\n'
                            '- the final frontend/user interface\n'
                            '- project-wide deployment architecture\n'
                            '- team-owned cybersecurity deliverables\n'
                            '- final human-validated accuracy evaluation\n'
                            '\n'
                            'Those areas should be merged into the final project documentation '
                            'from the corresponding verified team deliverables.\n',
 'backend-design-decisions.md': '> **Implementation scope:** RAVIN backend workstream\n'
                                '>\n'
                                '> **Backend checkpoint:** `5c8e2ce`\n'
                                '>\n'
                                '> **Verification baseline:** 725 passing tests\n'
                                '>\n'
                                '> **Purpose:** Source material for later project-wide '
                                'documentation\n'
                                '\n'
                                '# RAVIN Backend Design Decisions\n'
                                '\n'
                                '## 1. Purpose\n'
                                '\n'
                                'This document records major technical decisions implemented '
                                'during the RAVIN backend workstream and the reasoning behind '
                                'them.\n'
                                '\n'
                                '## 2. Evidence-First Control Architecture\n'
                                '\n'
                                'Generative language models are not used to control:\n'
                                '\n'
                                '- intent classification\n'
                                '- evidence sufficiency\n'
                                '- answer routing\n'
                                '- evidence release\n'
                                '\n'
                                'These decisions directly control whether RAVIN is allowed to '
                                'answer.\n'
                                '\n'
                                'Keeping them explicit and testable provides a more auditable '
                                'failure mode than asking a generative model to decide whether its '
                                'own response should be trusted.\n'
                                '\n'
                                'Generation is therefore restricted to wording an answer from '
                                'previously approved evidence.\n'
                                '\n'
                                '## 3. API Framework Comparison and FastAPI Selection\n'
                                '\n'
                                'Small proof-of-concept implementations were built for both '
                                'FastAPI and Flask during the backend framework comparison.\n'
                                '\n'
                                'The comparison verified that the backend contract could be '
                                'exposed through either framework before the project committed the '
                                'application layer to one framework.\n'
                                '\n'
                                'FastAPI was subsequently selected as the agreed API framework.\n'
                                '\n'
                                'The backend remains framework-neutral through '
                                '`RavinAnswerService`, so framework-specific request handling does '
                                'not need to be embedded into retrieval, routing, or generation '
                                'logic.\n'
                                '\n'
                                'The intended integration remains:\n'
                                '\n'
                                '```text\n'
                                'HTTP request\n'
                                '-> FastAPI validation\n'
                                '-> RavinAnswerService.answer()\n'
                                '-> JSON response\n'
                                '```\n'
                                '\n'
                                'This separation also reduces the cost of replacing the web '
                                'framework later because the implemented backend service does not '
                                'depend on FastAPI.\n'
                                '\n'
                                'The final FastAPI application layer is not claimed here as '
                                'implemented by this workstream.\n'
                                '\n'
                                '## 4. Replaceable Model Providers\n'
                                '\n'
                                'Model and library implementations are isolated behind provider '
                                'contracts.\n'
                                '\n'
                                'The project should not require business-logic changes simply '
                                'because an embedding model, reranker, parser, answerability '
                                'model, entailment model, or generation provider changes.\n'
                                '\n'
                                'Provider composition therefore occurs at startup.\n'
                                '\n'
                                '## 5. Local Language Model\n'
                                '\n'
                                'The implemented generation adapter uses a local Ollama service.\n'
                                '\n'
                                'Current default generation configuration:\n'
                                '\n'
                                '```text\n'
                                'provider -> ollama\n'
                                'model -> qwen3:4b-instruct\n'
                                'temperature -> 0\n'
                                '```\n'
                                '\n'
                                'A local model was suitable for the project because it avoids '
                                'requiring a paid hosted generation API and keeps the provider '
                                'replaceable.\n'
                                '\n'
                                '## 6. Hybrid Retrieval and Reranking\n'
                                '\n'
                                'Production retrieval combines semantic and lexical evidence '
                                'discovery.\n'
                                '\n'
                                'Current production configuration:\n'
                                '\n'
                                '```text\n'
                                'Top-K -> 5\n'
                                'rerank depth -> 11\n'
                                'semantic weight -> 0.85\n'
                                'lexical weight -> 0.15\n'
                                '```\n'
                                '\n'
                                'Candidate retrieval is followed by cross-encoder reranking.\n'
                                '\n'
                                'The retrieval layer deliberately separates candidate discovery '
                                'from evidence sufficiency.\n'
                                '\n'
                                '## 7. Production Body-Only Embeddings\n'
                                '\n'
                                'Production semantic embeddings use policy body text rather than '
                                'the complete title-heading-body retrieval text.\n'
                                '\n'
                                'The richer retrieval representation remains available for lexical '
                                'matching and reranking.\n'
                                '\n'
                                'This configuration emerged from retrieval experimentation rather '
                                'than being assumed initially.\n'
                                '\n'
                                '## 8. Structural Context Expansion\n'
                                '\n'
                                'Retrieval Top-K chunks are expanded with bounded neighbouring '
                                'chunks from the same policy heading.\n'
                                '\n'
                                'Default context configuration:\n'
                                '\n'
                                '```text\n'
                                'neighbor window -> 1\n'
                                'maximum context chunks -> 15\n'
                                '```\n'
                                '\n'
                                'This provides surrounding policy context while preserving an '
                                'explicit upper bound.\n'
                                '\n'
                                '## 9. Material Proposition Coverage\n'
                                '\n'
                                'A clear question is decomposed into material propositions.\n'
                                '\n'
                                'Evidence sufficiency then considers whether each material '
                                'proposition is:\n'
                                '\n'
                                '```text\n'
                                'COVERED\n'
                                'PARTIAL\n'
                                'UNCOVERED\n'
                                '```\n'
                                '\n'
                                'The deterministic outcome is:\n'
                                '\n'
                                '```text\n'
                                'any UNCOVERED\n'
                                '-> INSUFFICIENT\n'
                                '\n'
                                'any PARTIAL\n'
                                '-> UNCERTAIN\n'
                                '\n'
                                'all COVERED\n'
                                '-> SUFFICIENT\n'
                                '```\n'
                                '\n'
                                'This prevents one strong evidence match from masking another part '
                                'of a multi-part question that is unsupported.\n'
                                '\n'
                                '## 10. Clarification Versus No Grounded Answer\n'
                                '\n'
                                'These are intentionally different outcomes.\n'
                                '\n'
                                '`CLARIFY` means the question itself is not sufficiently resolved '
                                'to determine what evidence should answer it.\n'
                                '\n'
                                '`NO_GROUNDED_ANSWER` means the question is clear, but available '
                                'policy evidence has not been established as sufficient.\n'
                                '\n'
                                'This distinction is preserved throughout routing and service '
                                'results.\n'
                                '\n'
                                '## 11. Generated Citation Requirement\n'
                                '\n'
                                'Generated factual responses must cite supplied evidence using '
                                'approved evidence identifiers.\n'
                                '\n'
                                'A citation outside the supplied evidence range causes release '
                                'rejection.\n'
                                '\n'
                                '## 12. Generated Claim Validation\n'
                                '\n'
                                'Citation presence alone is not treated as proof of factual '
                                'support.\n'
                                '\n'
                                'Generated claims are also assessed against their cited policy '
                                'evidence through the entailment provider.\n'
                                '\n'
                                'Unsupported claims fail closed.\n'
                                '\n'
                                '## 13. Claim-Support Window Refinement\n'
                                '\n'
                                'An earlier approach evaluated generated claims against large '
                                'evidence blocks.\n'
                                '\n'
                                'During live validation, a genuine policy-supported re-admission '
                                'claim received an answerability-style score of approximately '
                                '`0.461832` and was incorrectly rejected.\n'
                                '\n'
                                'Investigation showed the claim was strongly supported when '
                                'evaluated against the relevant policy paragraph.\n'
                                '\n'
                                'The implementation was refined to construct deterministic '
                                'consecutive evidence windows of one to three textual units and '
                                'perform NLI entailment against those focused support windows.\n'
                                '\n'
                                'This allowed the release gate to assess the relevant evidence '
                                'instead of diluting the relationship inside a much larger block.\n'
                                '\n'
                                '## 14. Fail-Closed Generation\n'
                                '\n'
                                'When generated output fails required validation, RAVIN does not '
                                'fall back to releasing the unverified text.\n'
                                '\n'
                                'The backend prefers:\n'
                                '\n'
                                '```text\n'
                                'reject unsupported generated output\n'
                                '```\n'
                                '\n'
                                'over:\n'
                                '\n'
                                '```text\n'
                                'return plausible but unverified output\n'
                                '```\n'
                                '\n'
                                '## 15. Quality Threshold\n'
                                '\n'
                                'The project uses a minimum validated Top-1 retrieval quality '
                                'threshold of 95%.\n'
                                '\n'
                                'The threshold is a release/selection requirement.\n'
                                '\n'
                                'A development dataset passing 95% does not itself establish '
                                'validated system accuracy.\n'
                                '\n'
                                'Human-validated evaluation data is required before making a '
                                'validated accuracy claim.\n',
 'retrieval-and-quality-evaluation.md': '> **Implementation scope:** RAVIN backend workstream\n'
                                        '>\n'
                                        '> **Backend checkpoint:** `5c8e2ce`\n'
                                        '>\n'
                                        '> **Verification baseline:** 725 passing tests\n'
                                        '>\n'
                                        '> **Purpose:** Source material for later project-wide '
                                        'documentation\n'
                                        '\n'
                                        '# RAVIN Retrieval and Quality Evaluation\n'
                                        '\n'
                                        '## 1. Purpose\n'
                                        '\n'
                                        'This document records the evaluation framework '
                                        'implemented for the RAVIN backend.\n'
                                        '\n'
                                        'It distinguishes measured development performance from '
                                        'validated quality claims.\n'
                                        '\n'
                                        '## 2. Primary Retrieval Metrics\n'
                                        '\n'
                                        '### Top-1 Accuracy\n'
                                        '\n'
                                        'The proportion of evaluated Direct Answer questions for '
                                        'which expected evidence appears at rank 1.\n'
                                        '\n'
                                        '### Hit@K\n'
                                        '\n'
                                        'The proportion for which expected evidence appears '
                                        'anywhere within the configured Top-K.\n'
                                        '\n'
                                        '### Mean Reciprocal Rank\n'
                                        '\n'
                                        'MRR rewards systems that place the first relevant result '
                                        'closer to the top of the ranking.\n'
                                        '\n'
                                        '## 3. Quality Gate\n'
                                        '\n'
                                        'The configured minimum Top-1 threshold is 95%.\n'
                                        '\n'
                                        'Passing this numerical threshold is necessary but not '
                                        'sufficient for a validated result.\n'
                                        '\n'
                                        '## 4. Dataset Validation Status\n'
                                        '\n'
                                        'Evaluation datasets explicitly record validation status.\n'
                                        '\n'
                                        '```text\n'
                                        'PRELIMINARY\n'
                                        '-> suitable for development and optimisation\n'
                                        '-> cannot support a validated accuracy claim\n'
                                        '\n'
                                        'HUMAN_VALIDATED\n'
                                        '-> eligible for validated quality-gate evidence\n'
                                        '```\n'
                                        '\n'
                                        'This prevents development results from being presented as '
                                        'final system accuracy.\n'
                                        '\n'
                                        '## 5. Evaluation Population\n'
                                        '\n'
                                        'The evaluation framework tracks dataset behavior '
                                        'composition.\n'
                                        '\n'
                                        'Direct Answer questions are used for retrieval-ranking '
                                        'metrics.\n'
                                        '\n'
                                        'Other behaviors are recorded separately:\n'
                                        '\n'
                                        '- Grounded Overview\n'
                                        '- Clarify\n'
                                        '- No Grounded Answer\n'
                                        '\n'
                                        'This avoids applying ranking metrics to questions for '
                                        'which retrieval ranking is not the relevant expected '
                                        'behavior.\n'
                                        '\n'
                                        '## 6. Grounded Overview Evaluation\n'
                                        '\n'
                                        'Grounded Overview questions may require multiple evidence '
                                        'concepts.\n'
                                        '\n'
                                        'The implemented evaluation supports expected evidence '
                                        'groups, where each group may contain alternative '
                                        'acceptable evidence locations.\n'
                                        '\n'
                                        'A Grounded Overview question passes only when every '
                                        'required group is covered.\n'
                                        '\n'
                                        'The evaluation records:\n'
                                        '\n'
                                        '- total questions\n'
                                        '- passed questions\n'
                                        '- question pass rate\n'
                                        '- total evidence groups\n'
                                        '- covered evidence groups\n'
                                        '- evidence-group coverage\n'
                                        '\n'
                                        '## 7. Routing Evaluation\n'
                                        '\n'
                                        'Routing evaluation separately measures:\n'
                                        '\n'
                                        '- question intent\n'
                                        '- evidence sufficiency\n'
                                        '- final answer behavior\n'
                                        '\n'
                                        'Macro accuracy is used so performance across classes is '
                                        'visible rather than allowing a large class to dominate '
                                        'the result.\n'
                                        '\n'
                                        '## 8. Retrieval Experiment Framework\n'
                                        '\n'
                                        'The experiment framework compares a baseline and '
                                        'candidate using the same question population, Top-K, '
                                        'corpus, and evaluation configuration.\n'
                                        '\n'
                                        'It records:\n'
                                        '\n'
                                        '- Top-1 delta\n'
                                        '- Hit@K delta\n'
                                        '- MRR delta\n'
                                        '- per-question rank changes\n'
                                        '- relative direction\n'
                                        '- quality-gate result\n'
                                        '- dataset-validation result\n'
                                        '- candidate selection decision\n'
                                        '\n'
                                        '## 9. Reproducibility Evidence\n'
                                        '\n'
                                        'Experiment records contain provenance information '
                                        'including:\n'
                                        '\n'
                                        '- dataset SHA-256\n'
                                        '- corpus SHA-256\n'
                                        '- Git commit\n'
                                        '- generation timestamp\n'
                                        '- embedding provider and model\n'
                                        '- retrieval strategy\n'
                                        '- semantic and lexical weights\n'
                                        '- reranker provider and model\n'
                                        '- rerank depth\n'
                                        '\n'
                                        'Experiment recording requires a clean Git working tree.\n'
                                        '\n'
                                        '## 10. Development Retrieval Result\n'
                                        '\n'
                                        'The selected production retrieval configuration reached '
                                        'the development quality gate on the preliminary retrieval '
                                        'dataset used during optimisation.\n'
                                        '\n'
                                        'The recorded preliminary development result for the '
                                        'selected retrieval configuration was:\n'
                                        '\n'
                                        '```text\n'
                                        'Direct Answer Top-1 Accuracy -> 100%\n'
                                        'Hit@5 -> 100%\n'
                                        'MRR -> 1.0000\n'
                                        '```\n'
                                        '\n'
                                        'These values demonstrate performance on the preliminary '
                                        'development dataset only.\n'
                                        '\n'
                                        'They must not be represented as overall RAVIN accuracy or '
                                        'as evidence that the final system has achieved validated '
                                        '100% accuracy.\n'
                                        '\n'
                                        'The development result shows that the selected retrieval '
                                        "configuration satisfied the project's numerical "
                                        'development gate on that evaluation population.\n'
                                        '\n'
                                        '## 11. Human Validation Still Required\n'
                                        '\n'
                                        'A formal claim that RAVIN meets the 95% requirement '
                                        'requires a human-validated gold-standard question set.\n'
                                        '\n'
                                        'That work remains separate from the preliminary '
                                        'optimisation dataset.\n'
                                        '\n'
                                        '## 12. Continuous Improvement Pattern\n'
                                        '\n'
                                        '```text\n'
                                        'candidate change\n'
                                        '-> run evaluation\n'
                                        '-> compare against baseline\n'
                                        '-> inspect per-question changes\n'
                                        '-> check quality threshold\n'
                                        '-> check dataset validation status\n'
                                        '-> retain evidence record\n'
                                        '-> decide whether candidate is eligible\n'
                                        '```\n'
                                        '\n'
                                        'A candidate should not be adopted solely because it '
                                        'improves one metric relative to the baseline.\n',
 'backend-development-and-maintenance.md': '> **Implementation scope:** RAVIN backend workstream\n'
                                           '>\n'
                                           '> **Backend checkpoint:** `5c8e2ce`\n'
                                           '>\n'
                                           '> **Verification baseline:** 725 passing tests\n'
                                           '>\n'
                                           '> **Purpose:** Source material for later project-wide '
                                           'documentation\n'
                                           '\n'
                                           '# RAVIN Backend Development and Maintenance\n'
                                           '\n'
                                           '## 1. Purpose\n'
                                           '\n'
                                           'This document provides maintenance information for the '
                                           'implemented RAVIN backend.\n'
                                           '\n'
                                           'It is intended as technical source material for a '
                                           'later project-wide maintenance guide.\n'
                                           '\n'
                                           '## 2. Python Environment\n'
                                           '\n'
                                           'Development has been verified using the project '
                                           'virtual environment.\n'
                                           '\n'
                                           'Use:\n'
                                           '\n'
                                           '```powershell\n'
                                           '.\\.venv\\Scripts\\python.exe\n'
                                           '```\n'
                                           '\n'
                                           'rather than relying on a system Python installation.\n'
                                           '\n'
                                           '## 3. Runtime Configuration\n'
                                           '\n'
                                           '### Embeddings\n'
                                           '\n'
                                           '```text\n'
                                           'RAVIN_EMBEDDING_PROVIDER\n'
                                           'RAVIN_EMBEDDING_MODEL\n'
                                           '```\n'
                                           '\n'
                                           'Default:\n'
                                           '\n'
                                           '```text\n'
                                           'sentence_transformer\n'
                                           'sentence-transformers/all-MiniLM-L6-v2\n'
                                           '```\n'
                                           '\n'
                                           '### Reranking\n'
                                           '\n'
                                           '```text\n'
                                           'RAVIN_RERANKER_PROVIDER\n'
                                           'RAVIN_RERANKER_MODEL\n'
                                           '```\n'
                                           '\n'
                                           'Default:\n'
                                           '\n'
                                           '```text\n'
                                           'cross_encoder\n'
                                           'cross-encoder/ms-marco-MiniLM-L6-v2\n'
                                           '```\n'
                                           '\n'
                                           '### Question Parsing\n'
                                           '\n'
                                           '```text\n'
                                           'RAVIN_PRIMARY_PARSER_PROVIDER\n'
                                           'RAVIN_PRIMARY_PARSER_MODEL\n'
                                           'RAVIN_FALLBACK_PARSER_PROVIDER\n'
                                           'RAVIN_FALLBACK_PARSER_MODEL\n'
                                           '```\n'
                                           '\n'
                                           'Current primary default:\n'
                                           '\n'
                                           '```text\n'
                                           'spacy\n'
                                           'en_core_web_sm\n'
                                           '```\n'
                                           '\n'
                                           'Configured fallback:\n'
                                           '\n'
                                           '```text\n'
                                           'spacy\n'
                                           'en_core_web_md\n'
                                           '```\n'
                                           '\n'
                                           '### Answerability\n'
                                           '\n'
                                           '```text\n'
                                           'RAVIN_ANSWERABILITY_PROVIDER\n'
                                           'RAVIN_ANSWERABILITY_MODEL\n'
                                           '```\n'
                                           '\n'
                                           'Default:\n'
                                           '\n'
                                           '```text\n'
                                           'cross_encoder_answerability\n'
                                           'cross-encoder/qnli-electra-base\n'
                                           '```\n'
                                           '\n'
                                           '### Entailment\n'
                                           '\n'
                                           '```text\n'
                                           'RAVIN_ENTAILMENT_PROVIDER\n'
                                           'RAVIN_ENTAILMENT_MODEL\n'
                                           '```\n'
                                           '\n'
                                           'Default:\n'
                                           '\n'
                                           '```text\n'
                                           'cross_encoder_entailment\n'
                                           'cross-encoder/nli-deberta-v3-base\n'
                                           '```\n'
                                           '\n'
                                           '### Generation\n'
                                           '\n'
                                           '```text\n'
                                           'RAVIN_GENERATION_PROVIDER\n'
                                           'RAVIN_GENERATION_MODEL\n'
                                           '```\n'
                                           '\n'
                                           'Default:\n'
                                           '\n'
                                           '```text\n'
                                           'ollama\n'
                                           'qwen3:4b-instruct\n'
                                           '```\n'
                                           '\n'
                                           '## 4. Provider Registry\n'
                                           '\n'
                                           'Current provider identifiers include:\n'
                                           '\n'
                                           '- `sentence_transformer`\n'
                                           '- `cross_encoder`\n'
                                           '- `spacy`\n'
                                           '- `cross_encoder_answerability`\n'
                                           '- `cross_encoder_entailment`\n'
                                           '- `ollama`\n'
                                           '\n'
                                           'Business components consume neutral provider contracts '
                                           'rather than constructing these implementations '
                                           'directly.\n'
                                           '\n'
                                           '## 5. Runtime Prerequisites\n'
                                           '\n'
                                           'The current development backend has several runtime '
                                           'dependencies in addition to the Python environment.\n'
                                           '\n'
                                           'Live policy acquisition requires network access to the '
                                           'configured policy source.\n'
                                           '\n'
                                           'Grounded answer generation requires the configured '
                                           'Ollama service to be available and the configured '
                                           'generation model to be accessible to Ollama.\n'
                                           '\n'
                                           'Sentence Transformer and cross-encoder providers '
                                           'require their configured model resources to be '
                                           'available. Initial model use may involve downloading '
                                           'model files.\n'
                                           '\n'
                                           'The configured spaCy parsing model must also be '
                                           'available in the Python environment.\n'
                                           '\n'
                                           'A missing runtime dependency should be treated as a '
                                           'startup or provider configuration failure rather than '
                                           'silently bypassed.\n'
                                           '\n'
                                           '## 6. Shared Backend Bootstrap\n'
                                           '\n'
                                           'The service bootstrap:\n'
                                           '\n'
                                           '```text\n'
                                           'acquires policies\n'
                                           '-> processes chunks\n'
                                           '-> creates providers\n'
                                           '-> builds the production index\n'
                                           '-> constructs RavinAnswerService\n'
                                           '```\n'
                                           '\n'
                                           'A startup failure should be treated as a real backend '
                                           'failure rather than silently starting with missing '
                                           'evidence.\n'
                                           '\n'
                                           '## 7. Running the CLI\n'
                                           '\n'
                                           '```powershell\n'
                                           '.\\.venv\\Scripts\\python.exe -m scripts.run_ravin\n'
                                           '```\n'
                                           '\n'
                                           'The CLI is an adapter over the same shared '
                                           '`RavinAnswerService` intended for API integration.\n'
                                           '\n'
                                           '## 8. Running Tests\n'
                                           '\n'
                                           '```powershell\n'
                                           '.\\.venv\\Scripts\\python.exe -m pytest -q\n'
                                           '```\n'
                                           '\n'
                                           'Backend checkpoint `5c8e2ce` passed 725 tests.\n'
                                           '\n'
                                           '## 9. Documentation Audit\n'
                                           '\n'
                                           '```powershell\n'
                                           '.\\.venv\\Scripts\\python.exe -m '
                                           'scripts.audit_backend_documentation\n'
                                           '```\n'
                                           '\n'
                                           'At the documented checkpoint:\n'
                                           '\n'
                                           '```text\n'
                                           'modules documented -> 82/82\n'
                                           'public definitions documented -> 291/291\n'
                                           'parameters typed -> 171/171\n'
                                           'returns typed -> 171/171\n'
                                           'formatting violations -> 0\n'
                                           '```\n'
                                           '\n'
                                           '## 10. Retrieval Evaluation\n'
                                           '\n'
                                           'Development evaluation:\n'
                                           '\n'
                                           '```powershell\n'
                                           '.\\.venv\\Scripts\\python.exe -m '
                                           'scripts.run_retrieval_evaluation\n'
                                           '```\n'
                                           '\n'
                                           'Experiment runner:\n'
                                           '\n'
                                           '```powershell\n'
                                           '.\\.venv\\Scripts\\python.exe -m '
                                           'scripts.run_retrieval_experiment\n'
                                           '```\n'
                                           '\n'
                                           'These workflows may perform live policy acquisition '
                                           'and load model weights.\n'
                                           '\n'
                                           '## 11. Replacing a Provider\n'
                                           '\n'
                                           'A replacement provider should:\n'
                                           '\n'
                                           '1. implement the corresponding neutral protocol\n'
                                           '2. be registered in the provider factory registry\n'
                                           '3. be selectable through runtime configuration\n'
                                           '4. pass existing provider and integration tests\n'
                                           '5. be evaluated against the relevant development and '
                                           'validated datasets\n'
                                           '\n'
                                           'Do not put vendor-specific logic into routing or '
                                           'retrieval orchestration.\n'
                                           '\n'
                                           '## 12. Updating Policy Sources\n'
                                           '\n'
                                           'When extending the corpus, verify:\n'
                                           '\n'
                                           '- source URL\n'
                                           '- policy identifier\n'
                                           '- current status\n'
                                           '- successful extraction\n'
                                           '- non-empty normalized content\n'
                                           '- successful chunk production\n'
                                           '- source metadata retained in resulting chunks\n'
                                           '\n'
                                           '## 13. External Dependencies\n'
                                           '\n'
                                           'The implemented backend uses external libraries/models '
                                           'including:\n'
                                           '\n'
                                           '- Requests\n'
                                           '- Beautiful Soup\n'
                                           '- Sentence Transformers\n'
                                           '- cross-encoder models\n'
                                           '- spaCy\n'
                                           '- Ollama\n'
                                           '\n'
                                           'Exact dependency versions should ultimately be drawn '
                                           "from the project's dependency files when the final "
                                           'maintenance guide is assembled.\n'
                                           '\n'
                                           '## 14. Hugging Face Authentication Warning\n'
                                           '\n'
                                           'Model loading may display an unauthenticated Hugging '
                                           'Face warning.\n'
                                           '\n'
                                           'This warning has not prevented verified development '
                                           'execution.\n'
                                           '\n'
                                           '## 15. Startup Performance\n'
                                           '\n'
                                           'Model loading, live policy acquisition, embedding, '
                                           'indexing, and local generation can be comparatively '
                                           'expensive.\n'
                                           '\n'
                                           'For this reason the backend service should be '
                                           'constructed once and reused by application adapters.\n'
                                           '\n'
                                           '## 16. Failure Philosophy\n'
                                           '\n'
                                           'The backend deliberately surfaces several failures '
                                           'rather than silently continuing, including:\n'
                                           '\n'
                                           '- policy acquisition failure\n'
                                           '- empty policy content\n'
                                           '- invalid provider configuration\n'
                                           '- malformed model output\n'
                                           '- missing evidence citations\n'
                                           '- unsupported generated claims\n'
                                           '\n'
                                           'This behavior supports fail-closed answer '
                                           'generation.\n',
 'backend-handover.md': '> **Implementation scope:** RAVIN backend workstream\n'
                        '>\n'
                        '> **Backend checkpoint:** `5c8e2ce`\n'
                        '>\n'
                        '> **Verification baseline:** 725 passing tests\n'
                        '>\n'
                        '> **Purpose:** Source material for later project-wide documentation\n'
                        '\n'
                        '# RAVIN Backend Handover\n'
                        '\n'
                        '## 1. Purpose\n'
                        '\n'
                        'This document explains how another developer or application layer can '
                        'consume the implemented RAVIN backend.\n'
                        '\n'
                        'The primary application boundary is `RavinAnswerService`.\n'
                        '\n'
                        '## 2. Backend Entry Point\n'
                        '\n'
                        'Application code should construct the backend through the shared '
                        'bootstrap rather than rebuilding the RAG pipeline manually.\n'
                        '\n'
                        '```python\n'
                        'from backend.service.bootstrap import (\n'
                        '    create_current_policy_ravin_service,\n'
                        ')\n'
                        '\n'
                        'service = create_current_policy_ravin_service()\n'
                        '\n'
                        'result = service.answer(\n'
                        '    "What happens when a student is not making satisfactory academic '
                        'progress?"\n'
                        ')\n'
                        '```\n'
                        '\n'
                        '## 3. Service Lifecycle\n'
                        '\n'
                        '```text\n'
                        'application startup\n'
                        '-> create_current_policy_ravin_service()\n'
                        '-> retain service instance\n'
                        '\n'
                        'user request\n'
                        '-> service.answer(question)\n'
                        '\n'
                        'next user request\n'
                        '-> reuse same service\n'
                        '```\n'
                        '\n'
                        'Do not construct a new service for every question.\n'
                        '\n'
                        'Service creation can involve policy acquisition, ingestion, model '
                        'loading, corpus embedding, and retrieval index construction.\n'
                        '\n'
                        '## 4. Application-Facing Result\n'
                        '\n'
                        '`service.answer()` returns an `IntegratedAnswerResult`.\n'
                        '\n'
                        'The result includes:\n'
                        '\n'
                        '- `behavior`\n'
                        '- `answer`\n'
                        '- `grounded`\n'
                        '- `sources`\n'
                        '\n'
                        'Each grounded source exposes:\n'
                        '\n'
                        '- `policy_id`\n'
                        '- `title`\n'
                        '- `heading`\n'
                        '- `url`\n'
                        '\n'
                        'Application adapters should map this result into their own transport '
                        'format rather than exposing internal retrieval objects.\n'
                        '\n'
                        '## 5. Deterministic Behaviors\n'
                        '\n'
                        'Application code should expect:\n'
                        '\n'
                        '- `direct_answer`\n'
                        '- `grounded_overview`\n'
                        '- `clarify`\n'
                        '- `no_grounded_answer`\n'
                        '\n'
                        'The backend selects these behaviors.\n'
                        '\n'
                        'The API or UI should not independently reclassify the response.\n'
                        '\n'
                        '## 6. Clarification\n'
                        '\n'
                        'A clarification response represents an ambiguous question.\n'
                        '\n'
                        'It should not be treated as equivalent to a failed evidence search.\n'
                        '\n'
                        'A clarified user question should be submitted as a new question through '
                        'the normal backend pipeline.\n'
                        '\n'
                        '## 7. No Grounded Answer\n'
                        '\n'
                        'A no-grounded-answer result represents a clear question for which the '
                        'backend did not establish sufficient evidence.\n'
                        '\n'
                        'The consuming application should preserve this failure rather than asking '
                        'a language model to invent an alternative response.\n'
                        '\n'
                        '## 8. CLI Reference Adapter\n'
                        '\n'
                        '`scripts/run_ravin.py` is the implemented local adapter.\n'
                        '\n'
                        'It demonstrates the correct high-level pattern:\n'
                        '\n'
                        '```text\n'
                        'build service once\n'
                        '-> submit questions\n'
                        '-> print IntegratedAnswerResult\n'
                        '```\n'
                        '\n'
                        'The CLI should not itself be invoked from a web API.\n'
                        '\n'
                        'Both adapters should consume the same service.\n'
                        '\n'
                        '## 9. Example FastAPI Integration\n'
                        '\n'
                        '### Status\n'
                        '\n'
                        'The following is a handover/integration example.\n'
                        '\n'
                        'It demonstrates how the implemented backend should be consumed by a '
                        'FastAPI application.\n'
                        '\n'
                        'It does not claim that this FastAPI module is part of the completed '
                        'backend workstream.\n'
                        '\n'
                        '### Example\n'
                        '\n'
                        '```python\n'
                        'from contextlib import asynccontextmanager\n'
                        '\n'
                        'from fastapi import FastAPI\n'
                        'from fastapi import Request\n'
                        'from pydantic import BaseModel\n'
                        '\n'
                        'from backend.service.answer_service import RavinAnswerService\n'
                        'from backend.service.bootstrap import (\n'
                        '    create_current_policy_ravin_service,\n'
                        ')\n'
                        '\n'
                        '\n'
                        '@asynccontextmanager\n'
                        'async def lifespan(app: FastAPI):\n'
                        '    app.state.ravin_service = (\n'
                        '        create_current_policy_ravin_service()\n'
                        '    )\n'
                        '\n'
                        '    yield\n'
                        '\n'
                        '\n'
                        'app = FastAPI(\n'
                        '    lifespan=lifespan\n'
                        ')\n'
                        '\n'
                        '\n'
                        'class QuestionRequest(BaseModel):\n'
                        '    question: str\n'
                        '\n'
                        '\n'
                        '@app.post("/api/questions")\n'
                        'def answer_question(\n'
                        '    payload: QuestionRequest,\n'
                        '    request: Request,\n'
                        '):\n'
                        '    service: RavinAnswerService = (\n'
                        '        request.app.state.ravin_service\n'
                        '    )\n'
                        '\n'
                        '    result = service.answer(\n'
                        '        payload.question\n'
                        '    )\n'
                        '\n'
                        '    return {\n'
                        '        "answer": result.answer,\n'
                        '        "grounded": result.grounded,\n'
                        '        "sources": [\n'
                        '            {\n'
                        '                "policy_id": source.policy_id,\n'
                        '                "title": source.title,\n'
                        '                "heading": source.heading,\n'
                        '                "url": source.url,\n'
                        '            }\n'
                        '            for source in result.sources\n'
                        '        ],\n'
                        '    }\n'
                        '```\n'
                        '\n'
                        '## 10. Why Startup Construction Matters\n'
                        '\n'
                        '```text\n'
                        'FastAPI startup\n'
                        '-> policy acquisition\n'
                        '-> ingestion\n'
                        '-> model loading\n'
                        '-> embedding/index build\n'
                        '-> RavinAnswerService ready\n'
                        '```\n'
                        '\n'
                        'Individual HTTP requests then perform:\n'
                        '\n'
                        '```text\n'
                        'request validation\n'
                        '-> service.answer(question)\n'
                        '-> map result to JSON\n'
                        '```\n'
                        '\n'
                        'The API must not re-download policies, reload models, rebuild embeddings, '
                        'or rebuild the retrieval index for every request.\n'
                        '\n'
                        '## 11. Agreed HTTP Contract\n'
                        '\n'
                        'Project integration baseline:\n'
                        '\n'
                        '```text\n'
                        'POST /api/questions\n'
                        'Content-Type: application/json\n'
                        '```\n'
                        '\n'
                        'Example request:\n'
                        '\n'
                        '```json\n'
                        '{\n'
                        '  "question": "What does the policy say about special consideration?"\n'
                        '}\n'
                        '```\n'
                        '\n'
                        'Example grounded response shape:\n'
                        '\n'
                        '```json\n'
                        '{\n'
                        '  "answer": "Based on the available policy...",\n'
                        '  "grounded": true,\n'
                        '  "sources": [\n'
                        '    {\n'
                        '      "policy_id": "123",\n'
                        '      "title": "Policy Name",\n'
                        '      "heading": "Relevant Section",\n'
                        '      "url": "https://..."\n'
                        '    }\n'
                        '  ]\n'
                        '}\n'
                        '```\n'
                        '\n'
                        'Example no-evidence response shape:\n'
                        '\n'
                        '```json\n'
                        '{\n'
                        '  "answer": "I could not find sufficient evidence in the available policy '
                        'sources.",\n'
                        '  "grounded": false,\n'
                        '  "sources": []\n'
                        '}\n'
                        '```\n'
                        '\n'
                        'This section records the integration contract/pattern and should be '
                        'updated against the implemented API before it is treated as final API '
                        'documentation.\n'
                        '\n'
                        '## 12. Provider Replacement\n'
                        '\n'
                        'An integrating developer should not instantiate model providers inside '
                        'request handlers.\n'
                        '\n'
                        'Provider configuration belongs to runtime startup and composition.\n'
                        '\n'
                        '## 13. Backend Verification\n'
                        '\n'
                        'At backend checkpoint `5c8e2ce`:\n'
                        '\n'
                        '```text\n'
                        '725 tests passed\n'
                        '82/82 modules documented\n'
                        '291/291 public definitions documented\n'
                        '171/171 public callable parameters typed\n'
                        '171/171 public callable returns typed\n'
                        '```\n'
                        '\n'
                        '## 14. Integration Work Outside This Handover\n'
                        '\n'
                        'This backend handover does not claim completion of:\n'
                        '\n'
                        '- final FastAPI routes\n'
                        '- frontend integration\n'
                        '- final deployment environment\n'
                        '- authentication/authorization\n'
                        '- project-wide security configuration\n'
                        '- final production monitoring\n'
                        '\n'
                        'Those should be documented from the relevant implemented project work.\n',
 'backend-known-limitations.md': '> **Implementation scope:** RAVIN backend workstream\n'
                                 '>\n'
                                 '> **Backend checkpoint:** `5c8e2ce`\n'
                                 '>\n'
                                 '> **Verification baseline:** 725 passing tests\n'
                                 '>\n'
                                 '> **Purpose:** Source material for later project-wide '
                                 'documentation\n'
                                 '\n'
                                 '# RAVIN Backend Known Limitations\n'
                                 '\n'
                                 '## 1. Purpose\n'
                                 '\n'
                                 'This document records limitations observed or identified during '
                                 'the implemented backend workstream.\n'
                                 '\n'
                                 'It is intentionally limited to known backend evidence rather '
                                 'than speculating about unfinished project components.\n'
                                 '\n'
                                 '## 2. Accuracy Is Not Yet a Validated Final Claim\n'
                                 '\n'
                                 'Development retrieval evaluation has produced strong preliminary '
                                 'results.\n'
                                 '\n'
                                 'However, the current development dataset is explicitly '
                                 'preliminary.\n'
                                 '\n'
                                 'Therefore the project cannot use those results alone to claim '
                                 'that RAVIN is 95% accurate.\n'
                                 '\n'
                                 'A human-validated gold-standard evaluation set is still required '
                                 'for a validated quality claim.\n'
                                 '\n'
                                 '## 3. Development Thresholds Require Calibration\n'
                                 '\n'
                                 'Some answerability and generated-claim support thresholds remain '
                                 'development controls.\n'
                                 '\n'
                                 'They should be calibrated against appropriately validated data '
                                 'before being treated as final production operating thresholds.\n'
                                 '\n'
                                 '## 4. Live Runtime Latency\n'
                                 '\n'
                                 'A live vertical-slice execution involving policy acquisition, '
                                 'multiple model providers, local generation, and claim validation '
                                 'took approximately 252 seconds in development.\n'
                                 '\n'
                                 'This is sufficient to demonstrate integration but is not an '
                                 'acceptable final interactive latency target.\n'
                                 '\n'
                                 'Performance optimisation remains necessary.\n'
                                 '\n'
                                 '## 5. Policy Text Encoding\n'
                                 '\n'
                                 'Live policy material has shown encoding/mojibake artifacts where '
                                 'source characters are decoded into incorrect character '
                                 'sequences.\n'
                                 '\n'
                                 'The problem was identified but intentionally deferred while '
                                 'backend architecture and documentation were being checkpointed.\n'
                                 '\n'
                                 'The acquisition and normalization path should be checked for '
                                 'encoding handling before final presentation-quality output.\n'
                                 '\n'
                                 '## 6. Visible Evidence Markers\n'
                                 '\n'
                                 'Grounded generation currently uses visible evidence markers such '
                                 'as `[E1]` and `[E2]`.\n'
                                 '\n'
                                 'These markers provide useful traceability for validation.\n'
                                 '\n'
                                 'The final UI may choose to transform them into more '
                                 'user-friendly source presentation while retaining backend '
                                 'evidence traceability.\n'
                                 '\n'
                                 '## 7. Model Download Warning\n'
                                 '\n'
                                 'Hugging Face model loading may emit an unauthenticated access '
                                 'warning.\n'
                                 '\n'
                                 'This has not blocked development execution.\n'
                                 '\n'
                                 '## 8. Parser Edge Cases\n'
                                 '\n'
                                 'Question parsing includes fallback and deterministic recovery '
                                 'because dependency parsing can produce structurally suspicious '
                                 'analyses.\n'
                                 '\n'
                                 'At least one development routing question exposed an additional '
                                 'parser hardening case.\n'
                                 '\n'
                                 'This remains a known hardening item rather than a reason to '
                                 'reopen the completed routing architecture.\n'
                                 '\n'
                                 '## 9. Current Policy Corpus\n'
                                 '\n'
                                 'The shared bootstrap currently uses the policy set included in '
                                 'the implemented development vertical slice.\n'
                                 '\n'
                                 'The final application may require a broader current-policy '
                                 'corpus and a maintained refresh process.\n'
                                 '\n'
                                 '## 10. FastAPI Integration\n'
                                 '\n'
                                 'The shared backend service is ready to be consumed by an API '
                                 'adapter.\n'
                                 '\n'
                                 'The example FastAPI integration in the handover is an '
                                 'integration pattern, not evidence that the final project API '
                                 'layer has been implemented by this workstream.\n'
                                 '\n'
                                 '## 11. User Interface\n'
                                 '\n'
                                 'No final user-interface behavior is documented here as completed '
                                 'backend work.\n'
                                 '\n'
                                 'User documentation should be produced from the final verified '
                                 'application interface.\n'
                                 '\n'
                                 '## 12. Final Security and Deployment\n'
                                 '\n'
                                 'Project-wide production security, deployment, monitoring, and '
                                 'operational procedures require evidence from the corresponding '
                                 'completed team deliverables.\n'
                                 '\n'
                                 'They should not be inferred from the backend implementation '
                                 'alone.\n'}

def write_document(
    filename: str,
    content: str,
) -> bool:
    """Write one generated document when its configured content changed."""

    DOCS_DIRECTORY.mkdir(
        parents=True,
        exist_ok=True,
    )

    path = DOCS_DIRECTORY / filename
    normalized = content.rstrip() + "\n"

    if path.exists():
        existing = path.read_text(
            encoding="utf-8"
        )

        if existing == normalized:
            print(f"Unchanged -> {path}")
            return False

    path.write_text(
        normalized,
        encoding="utf-8",
    )

    print(f"Written -> {path}")
    return True

def main() -> int:
    """Generate every configured RAVIN backend source document."""

    changed = 0

    for filename, content in DOCUMENTS.items():
        if write_document(
            filename,
            content,
        ):
            changed += 1

    print()
    print(
        "Documents configured -> "
        f"{len(DOCUMENTS)}"
    )

    print(
        "Documents changed -> "
        f"{changed}"
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
